Python 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> 
========================== RESTART: E:\Projekt 9.py ==========================
Unhandled exception in thread started by <function eval_bally at 0x0000025C48C49BF8>
Traceback (most recent call last):
  File "E:\Projekt 9.py", line 147, in eval_bally
    x1, y1, x2, y2 = canvas.coords(seite_pc)
  File "C:\Program Files\Python36\lib\tkinter\__init__.py", line 2463, in coords
    self.tk.call((self._w, 'coords') + args))]
_tkinter.TclError: invalid command name ".!canvas3"
Unhandled exception in thread started by <function eval_bally at 0x0000025C48C49BF8>
Traceback (most recent call last):
  File "E:\Projekt 9.py", line 153, in eval_bally
    x1, y1, x2, y2 = canvas.coords(o)
  File "C:\Program Files\Python36\lib\tkinter\__init__.py", line 2463, in coords
    self.tk.call((self._w, 'coords') + args))]
_tkinter.TclError: invalid command name ".!canvas10"
>>> Unhandled exception in thread started by Unhandled exception in thread started by <function eval_bally at 0x0000025C48C49BF8><function eval_ballx at 0x0000025C48C49B70>

Traceback (most recent call last):
Traceback (most recent call last):
  File "E:\Projekt 9.py", line 147, in eval_bally
  File "E:\Projekt 9.py", line 120, in eval_ballx
        x1, y1, x2, y2 = canvas.coords(seite_pc)x1, y1, x2, y2 = canvas.coords(seite_user)

  File "C:\Program Files\Python36\lib\tkinter\__init__.py", line 2463, in coords
  File "C:\Program Files\Python36\lib\tkinter\__init__.py", line 2463, in coords
    self.tk.call((self._w, 'coords') + args))]    
self.tk.call((self._w, 'coords') + args))]_tkinter
._tkinterTclError.: TclErrorinvalid command name ".!canvas13": 
invalid command name ".!canvas13"
Unhandled exception in thread started by <function move_ball at 0x0000025C48C49AE8>
Traceback (most recent call last):
  File "E:\Projekt 9.py", line 110, in move_ball
    canvas.coords(ball, int(x_real), int(y_real), int(x_real)+15, int(y_real)+15)
  File "C:\Program Files\Python36\lib\tkinter\__init__.py", line 2463, in coords
    self.tk.call((self._w, 'coords') + args))]
RuntimeError: main thread is not in main loop

========================== RESTART: E:\Projekt 9.py ==========================
Unhandled exception in thread started by <function eval_bally at 0x000001D80C378BF8>
Traceback (most recent call last):
  File "E:\Projekt 9.py", line 151, in eval_bally
    x1, y1, x2, y2 = canvas.coords(seite_pc)
  File "C:\Program Files\Python36\lib\tkinter\__init__.py", line 2463, in coords
    self.tk.call((self._w, 'coords') + args))]
_tkinter.TclError: invalid command name ".!canvas"
Unhandled exception in thread started by <function eval_bally at 0x000001D80C378BF8>
Traceback (most recent call last):
  File "E:\Projekt 9.py", line 151, in eval_bally
    x1, y1, x2, y2 = canvas.coords(seite_pc)
  File "C:\Program Files\Python36\lib\tkinter\__init__.py", line 2463, in coords
    self.tk.call((self._w, 'coords') + args))]
_tkinter.TclError: invalid command name ".!canvas5"
Unhandled exception in thread started by <function eval_ballx at 0x000001D80C378B70>
Traceback (most recent call last):
  File "E:\Projekt 9.py", line 123, in eval_ballx
    time.sleep()
TypeError: sleep() takes exactly one argument (0 given)
>>> 
========================== RESTART: E:\Projekt 9.py ==========================
Unhandled exception in thread started by <function eval_bally at 0x0000015EC1C4CBF8>
Traceback (most recent call last):
  File "E:\Projekt 9.py", line 151, in eval_bally
    x1, y1, x2, y2 = canvas.coords(seite_pc)
  File "C:\Program Files\Python36\lib\tkinter\__init__.py", line 2463, in coords
    self.tk.call((self._w, 'coords') + args))]
_tkinter.TclError: invalid command name ".!canvas4"

========================== RESTART: E:\Projekt 9.py ==========================
Unhandled exception in thread started by <function eval_bally at 0x00000146519ECC80>
Traceback (most recent call last):
  File "E:\Projekt 9.py", line 155, in eval_bally
    x1, y1, x2, y2 = canvas.coords(seite_pc)
  File "C:\Program Files\Python36\lib\tkinter\__init__.py", line 2463, in coords
    self.tk.call((self._w, 'coords') + args))]
_tkinter.TclError: invalid command name ".!canvas2"

========================== RESTART: E:\Projekt 9.py ==========================
>>> Unhandled exception in thread started by Unhandled exception in thread started by <function eval_bally at 0x0000024838DFCC80><function eval_ballx at 0x0000024838DFCBF8>

Traceback (most recent call last):
Traceback (most recent call last):
  File "E:\Projekt 9.py", line 155, in eval_bally
  File "E:\Projekt 9.py", line 124, in eval_ballx
        x1, y1, x2, y2 = canvas.coords(seite_pc)x1, y1, x2, y2 = canvas.coords(seite_user)

  File "C:\Program Files\Python36\lib\tkinter\__init__.py", line 2463, in coords
  File "C:\Program Files\Python36\lib\tkinter\__init__.py", line 2463, in coords
    self.tk.call((self._w, 'coords') + args))]    
self.tk.call((self._w, 'coords') + args))]_tkinter
._tkinterTclError.: TclErrorinvalid command name ".!canvas2": 
invalid command name ".!canvas2"
Unhandled exception in thread started by <function move_ball at 0x0000024838DFCB70>
Traceback (most recent call last):
  File "E:\Projekt 9.py", line 110, in move_ball
    canvas.coords(ball, int(x_real), int(y_real), int(x_real)+15, int(y_real)+15)
  File "C:\Program Files\Python36\lib\tkinter\__init__.py", line 2463, in coords
    self.tk.call((self._w, 'coords') + args))]
RuntimeError: main thread is not in main loop

========================== RESTART: E:\Projekt 9.py ==========================
Unhandled exception in thread started by <function eval_bally at 0x00000246D43DCBF8>
Traceback (most recent call last):
  File "E:\Projekt 9.py", line 150, in eval_bally
    x1, y1, x2, y2 = canvas.coords(seite_user)
  File "C:\Program Files\Python36\lib\tkinter\__init__.py", line 2463, in coords
    self.tk.call((self._w, 'coords') + args))]
_tkinter.TclError: invalid command name ".!canvas"
Unhandled exception in thread started by <function eval_bally at 0x00000246D43DCBF8>
Traceback (most recent call last):
  File "E:\Projekt 9.py", line 155, in eval_bally
    x1, y1, x2, y2 = canvas.coords(seite_pc)
  File "C:\Program Files\Python36\lib\tkinter\__init__.py", line 2463, in coords
    self.tk.call((self._w, 'coords') + args))]
_tkinter.TclError: invalid command name ".!canvas3"
Unhandled exception in thread started by <function eval_bally at 0x00000246D43DCBF8>
Traceback (most recent call last):
  File "E:\Projekt 9.py", line 155, in eval_bally
    x1, y1, x2, y2 = canvas.coords(seite_pc)
  File "C:\Program Files\Python36\lib\tkinter\__init__.py", line 2463, in coords
    self.tk.call((self._w, 'coords') + args))]
_tkinter.TclError: invalid command name ".!canvas4"
Unhandled exception in thread started by <function eval_bally at 0x00000246D43DCBF8>
Traceback (most recent call last):
  File "E:\Projekt 9.py", line 155, in eval_bally
    x1, y1, x2, y2 = canvas.coords(seite_pc)
  File "C:\Program Files\Python36\lib\tkinter\__init__.py", line 2463, in coords
    self.tk.call((self._w, 'coords') + args))]
_tkinter.TclError: invalid command name ".!canvas6"
Unhandled exception in thread started by <function eval_bally at 0x00000246D43DCBF8>
Traceback (most recent call last):
  File "E:\Projekt 9.py", line 155, in eval_bally
    x1, y1, x2, y2 = canvas.coords(seite_pc)
  File "C:\Program Files\Python36\lib\tkinter\__init__.py", line 2463, in coords
    self.tk.call((self._w, 'coords') + args))]
_tkinter.TclError: invalid command name ".!canvas8"
Unhandled exception in thread started by <function eval_bally at 0x00000246D43DCBF8>
Traceback (most recent call last):
  File "E:\Projekt 9.py", line 150, in eval_bally
    x1, y1, x2, y2 = canvas.coords(seite_user)
  File "C:\Program Files\Python36\lib\tkinter\__init__.py", line 2463, in coords
    self.tk.call((self._w, 'coords') + args))]
_tkinter.TclError: invalid command name ".!canvas13"
>>> 
